### ISSUE TITLE
Generate sitemap for a huge collection

### ISSUE THREAD

**Issue by denisjankovic** [boazpoolman/strapi-plugin-sitemap#125]
I'm looking to generate a sitemap for collection with 35000 pages, when I add it to the sitemap plugin configuration, the plugin craches and don't want to generate the sitemap.

**Comment by boazpoolman** [comment]
Thanks for reporting this issue @denisjankovic.

I've been working hard on improving performance the past few weeks.
I'll release a new major version (3.0.0) soon which includes all these fixes.
I've tested that new version myself with 50.000 URLs and that worked fine.
I'm aware of the current release (2.0.11) being very bad in terms of performance of large sitemaps.

You could try out this new version by pulling the repo.
Otherwise please be patient for the new major release.

**Comment by denisjankovic** [comment]
Thank you for the fast answare. I will wait for the next release, do you know when you will release it ? 

I have an other question, can we have later a feature to create multiple sitemap files and group them all in one ? 
Example :
- web_pages_1.xml
- web_pages_2.xml
etc
And then group them all in a global one ? 

Thanks a lot for you answare.

**Comment by boazpoolman** [comment]
I'm waiting for the next release of Strapi to release v3.
I hope that'll be tomorrow.

About your question:
In version 3 you can split your sitemap into chunks and group them together in a sitemap index.
See issue #66 

Is that what you're looking for?

**Comment by denisjankovic** [comment]
Yes, it's exactly what I'm looking for. Thanks a lot, I'll just wait for the new release.
Best regards,

**Comment by boazpoolman** [comment]
I'll keep you posted.

**Comment by boazpoolman** [comment]
Hi @denisjankovic 

Just letting you know that I've just released [version 3.0.0](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/3.0.0) of the Sitemap plugin.

It would be amazing if you could test out that version and see if you are able to generate the sitemap with 35.000 URLs.
