### ISSUE TITLE
Add an additional link tag with hreflang x-default to improve locale detection fallback

### ISSUE THREAD

**Issue by RomainGueffier** [boazpoolman/strapi-plugin-sitemap#161]
Hello, thank you for this really useful plugin !

### Summary

Add a `link` tag with `hreflang="x-default"`

### Why is it needed?

Ahref SEO software rises advice to enable link tag with hreflang x-default value for default language fallback.
Google also mentions it: https://developers.google.com/search/blog/2023/05/x-default?hl=en

It is not necessary nor seems to penalise seo. But I would like to know your opinion on it?

### Suggested solution(s)

Add the additional `link` tag with `hreflang="x-default"` value from default locale pathname.
I could contribute if needed 😃

**Comment by RomainGueffier** [comment]
Glad you like the idea 🚀 ! I don't need the use case with a specific neutral page having language selector, but it should be done for sure.

I'm not sure how to make good UI/UX. As global option seems good to choose between:
- disabled (default?)
- a specific path
- generate from default language pathname on every **internationalised** url bundles

No need for per-bundle settings if so.

What do you think?

**Comment by boazpoolman** [comment]
Yep that sounds like a plan.

So that would be an extra select input (dropdown) in this section:
<img width="1009" alt="Scherm­afbeelding 2024-03-08 om 10 18 42" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/9551934/22c82cf5-4e40-4ee2-b96f-15575cbd6b6d">

And the values of that select input can be:
- Disabled
- Default language pathname
- Other

And when somebody selects the Other option an extra text input field should show in which the user can put the path of their choice.

And yeah just have disabled be the default makes sense. That would make this backwards compatible as well.

@RomainGueffier Do you want to make this contribution?

**Comment by RomainGueffier** [comment]
@boazpoolman deal! I will create PR soon.
