### ISSUE TITLE
Use of non UID type field

### ISSUE THREAD

**Issue by boazpoolman** [boazpoolman/strapi-plugin-sitemap#19]
This plugin has been written to use UID type fields as URLs to build the sitemap xml.
Potentially we could use a non UID field as (part of the) URL, to use the ID field for example.

This is kind of an interest check. If this is something you would like to see, let me know in this issue.
If this is highly requested I will update the plugin.

**Comment by boazpoolman** [comment]
Regarding the inclusion of relationship fields in the URL I'd suggest for now at least we also only allow the ID and UID type fields of the relationship. This way we will ensure the URL will consist only of fields which are actually usable in a URL (no spaces e.g.).

**Comment by boazpoolman** [comment]
This is now in the develop branch, will be released with the next minor/major release.
You are able to test this like so:

`yarn add boazpoolman/strapi-plugin-sitemap#develop`
`npm install boazpoolman/strapi-plugin-sitemap#develop`

**Comment by julesrenaud** [comment]
I think any field should be allowed, not just the ID or a field with type UID. When using i18n the UID field type is problematic if used as a slug system because a slug can then only be used once. Sometimes the same slug needs to be used for multiple separate locales (e.g. /en/contact in English and /fr/contact in French). I think it's resonable to assume any field used as a slug will be properly slugified via a lifecycle hook. https://strapi.io/documentation/developer-docs/latest/guides/slug.html

**Comment by boazpoolman** [comment]
Released in [v2.0.0](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/2.0.0) for the Strapi v4 version of `strapi-plugin-sitemap`.

**Comment by SalahAdDin** [comment]
@boazpoolman so, right now we can use `slug` for create the sitemap, right?

**Comment by boazpoolman** [comment]
Hey @SalahAdDin

In strapi-plugin-sitemap ^2.0.0 you can use URL patterns.
In the pattern you can inject dynamic values. 
Those can be ID's, UID's or any other field type.

See documentation here:
https://github.com/boazpoolman/strapi-plugin-sitemap#-url-pattern
